name: CD

on:
  push:
    branches:
      - main

concurrency:
  group: CD

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: https://starchart.fly.dev
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.2.8
      - run: flyctl deploy -c ./fly.toml --remote-only --build-secret="SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN" --build-arg="SENTRY_RELEASE=$GITHUB_SHA"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: getsentry/action-release@586b62368d564f25d694ce05fcb9cf53de65ac4f # v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: topplethenun
          SENTRY_PROJECT: starchart
        with:
          environment: production
